# This script is generated by SensorGatewayUtil.sh to run the custom sensor. The data is embbeded at the end of this file. 
# This script enables the sensor to run in a gateway, which is compatible with iCOMOT
# The settings of the sensor is:
#    Dataset = ./gps1279.data
#    Maxlines = 0
#    Columns =  
#    Protocol = dry 
#    Frequency = 3
# This script requires sensor.tar.gz in the same folder. If not, please uncomment following line.
# wget https://github.com/tuwiendsg/iCOMOT/raw/master/examples/sensors/sensor.tar.gz

if [ ! -f ./sensor.tar.gz ]; then
	echo "Sensor artifact does not found!" | tee /tmp/sensor.err
  exit 1;
fi

CURRENT_DIR=$(pwd)

# prepare sensor artifact for the iCOMOT-compatible gateway
tar -xvzf ./sensor.tar.gz
touch sensor.pid
chmod 777 sensor.pid
rm sensor.tar.gz

# replace the data
cd $CURRENT_DIR
sed '1,/^START OF DATA/d' $0 > data.csv
mv data.csv ./config-files/data.csv

# configure the sensor in META-INF
sed -i 's#<bean id="producer" class="at.ac.tuwien.infosys.cloudconnectivity.dryrun.Dryrun" />#<bean id="producer" class="at.ac.tuwien.infosys.cloudconnectivity.mqtt.MQProducer" />#' config-files/META-INF/wire.xml
sed -i 's#<property name="updateRate" value=.*#<property name="updateRate" value="3"/>#' config-files/META-INF/wire.xml

# With the distributed version, sensor is not started.
bash ./container_run_bg.sh
exit 0

START OF DATA
gps1279,gp1279,data,gps1279,10.71232,106.73684
gps1279,gp1279,data,gps1279,10.71232,106.73683
gps1279,gp1279,data,gps1279,10.71232,106.73684
gps1279,gp1279,data,gps1279,10.71232,106.73684
gps1279,gp1279,data,gps1279,10.71232,106.73684
gps1279,gp1279,data,gps1279,10.71232,106.73684
gps1279,gp1279,data,gps1279,10.71232,106.73684
gps1279,gp1279,data,gps1279,10.71232,106.73684
